imports:
  - path: instance-template.jinja

resources:
  # Create the auto-mode network
  #  gcloud deployment-manager types list | grep network
  - name: mynetwork
    type: compute.v1.network
    properties:
      autoCreateSubnetworks: true

  # Create the firewall rule
  #  gcloud deployment-manager types list | grep firewall
  - name: mynetwork-allow-http-ssh-rdp-icmp
    type: compute.v1.firewall
    properties:
      network: $(ref.mynetwork.selfLink)
      sourceRanges: ["0.0.0.0/0"]
      allowed:
        - IPProtocol: TCP
          ports: [22, 80, 3389]
        - IPProtocol: ICMP

  # Create the mynet-us-vm instance
  - name: mynet-us-vm
    type: instance-template.jinja
    properties:
      zone: us-central1-a
      machineType: n1-standard-1
      network: $(ref.mynetwork.selfLink)
      subnetwork: regions/us-central1/subnetworks/mynetwork

  # Create the mynet-eu-vm instance
  - name: mynet-eu-vm
    type: instance-template.jinja
    properties:
      zone: europe-west1-d
      machineType: n1-standard-1
      network: $(ref.mynetwork.selfLink)
      subnetwork: regions/europe-west1/subnetworks/mynetwork

# Preview
# gcloud deployment-manager deployments create dminfra --config=config.yaml --preview

# Create Deployment
# gcloud deployment-manager deployments update dminfra

# Delete Deployment
# gcloud deployment-manager deployments delete dminfra
